##################################################
# User peripheral sources
##################################################
ACCELERATOR_SRCS = $(abspath $(addprefix $(BASE_DIR)/../accelerator/, \
accelerator.v \
axi4_lite_slave.v \
axi4_stream_master.v \
axi4_stream_dest_generator.v \
axi_demux.v \
global_settings.v \
ps_pl_interface.v \
))
